---
deployment:
  tasks:
    - export DEPLOYPATH=/home/enviarex/public_html/
    -/bin/rsync -av --exclude='.git/' --exclude='.gitignore' --exclude='model/db.php' --exclude='admin/config.php' -r api assets controller model view $DEPLOYPATH